// The Groq-generated narrative. Given a distinct "analyst note" treatment —
// navy panel, gold rule, serif lead — so it reads as considered commentary that
// sits above the raw signals, not another data row.
// The LLM sometimes returns light markdown (**bold**). Render those spans as
// real emphasis instead of leaking asterisks to the user.
function renderInline(text, keyPrefix) {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    const m = part.match(/^\*\*([^*]+)\*\*$/);
    if (m) return <strong key={`${keyPrefix}-${i}`} className="font-semibold text-paper">{m[1]}</strong>;
    return part;
  });
}

export default function AiAnalystPanel({ explanation }) {
  if (!explanation || !explanation.summary) return null;
  const paragraphs = explanation.summary
    .split(/\n{2,}|\n/)
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <section className="relative overflow-hidden rounded-2xl bg-ink text-paper shadow-md">
      {/* Ambient gold wash */}
      <div
        className="pointer-events-none absolute -right-16 -top-20 h-56 w-56 rounded-full opacity-30 blur-2xl"
        style={{ background: "radial-gradient(circle, var(--gold-soft), transparent 70%)" }}
      />
      <div className="relative p-6 sm:p-7">
        <div className="mb-4 flex items-center gap-3">
          <span className="flex h-9 w-9 items-center justify-center rounded-full border border-gold-soft/40 text-gold-soft">
            {/* spark / analyst glyph */}
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <path d="M12 2l1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8L12 2z"
                    fill="currentColor" />
            </svg>
          </span>
          <div>
            <h3 className="font-display text-lg leading-none">Analyst Summary</h3>
            <p className="mt-1 text-xs tracking-wide text-paper/55">
              AI-generated · grounded in the signals below
            </p>
          </div>
        </div>

        <div className="space-y-3 text-[15px] leading-relaxed text-paper/90">
          {paragraphs.map((p, i) => (
            <p key={i} className={i === 0 ? "font-display text-[17px] leading-relaxed text-paper" : ""}>
              {renderInline(p, i)}
            </p>
          ))}
        </div>

        <p className="mt-5 border-t border-paper/15 pt-3 text-[11px] tracking-wide text-paper/45">
          Generated by {explanation.model} · a narrative explanation, not an independent verdict
        </p>
      </div>
    </section>
  );
}
